spring:
  application:
    name: companyinfo-service
  config:
    import: optional:configserver:http://localhost:8888

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # create에서 update로 변경
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

# Server Configuration
server:
  port: 8084

# Logging Configuration
logging:
  level:
    com.hermes.companyinfoservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cloud.config: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
