spring:
  application:
    name: attendance-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

# Server Configuration
server:
  port: 8089

# Attendance Service Configuration
attendance:
  start-time: "09:00"
  end-time: "18:00"

# Leave Service Configuration
leave:
  max-annual-leave: 15
  max-sick-leave: 10

# Work Policy Service Configuration
workpolicy:
  default-work-hours: 8
  default-work-minutes: 0
  max-weekly-hours: 40

# Eureka Client Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

# Swagger OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.hermes.attendanceservice.controller
