server:
  port: 8077

spring:
  application:
    name: news-crawler-service
  config:
    import:
      - optional:configserver:http://localhost:8888
      - optional:application-secret.yml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    time-zone: Asia/Seoul

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
