spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**,/api/auth/**,/api/v1/titles/**
            - id: news-crawler-service
              uri: lb://news-crawler-service
              predicates:
                - Path=/api/news/**
            - id: approval-service
              uri: lb://approval-service
              predicates:
                - Path=/api/approval/**
            - id: communication-service-websocket
              uri: lb:ws://communication-service
              predicates:
                - Path=/ws/**,/ws-pure/**
            - id: communication-service
              uri: lb://communication-service
              predicates:
                - Path=/api/announcements/**,/api/comments/**,/api/notifications/**,/api/archives/**
            - id: attendance-service
              uri: lb://attendance-service
              predicates:
                - Path=/api/attendance/**,/api/leaves/**,/api/workpolicy/**,/api/work-schedule/**,/api/aichat/**
            - id: attachment-service
              uri: lb://attachment-service
              predicates:
                - Path=/api/attachments/**
            - id: org-service
              uri: lb://org-service
              predicates:
                - Path=/api/organizations/**,/api/assignments/**

            # API 문서 라우팅
            - id: user-service-docs
              uri: lb://user-service
              predicates:
                - Path=/v3/api-docs/user-service
              filters:
                - RewritePath=/v3/api-docs/user-service, /v3/api-docs
            - id: approval-service-docs
              uri: lb://approval-service
              predicates:
                - Path=/v3/api-docs/approval-service
              filters:
                - RewritePath=/v3/api-docs/approval-service, /v3/api-docs
            - id: tenant-service-docs
              uri: lb://tenant-service
              predicates:
                - Path=/v3/api-docs/tenant-service
              filters:
                - RewritePath=/v3/api-docs/tenant-service, /v3/api-docs
            - id: org-service-docs
              uri: lb://org-service
              predicates:
                - Path=/v3/api-docs/org-service
              filters:
                - RewritePath=/v3/api-docs/org-service, /v3/api-docs
            - id: attendance-service-docs
              uri: lb://attendance-service
              predicates:
                - Path=/v3/api-docs/attendance-service
              filters:
                - RewritePath=/v3/api-docs/attendance-service, /v3/api-docs
            - id: news-service-docs
              uri: lb://news-crawler-service
              predicates:
                - Path=/v3/api-docs/news-service
              filters:
                - RewritePath=/v3/api-docs/news-service, /v3/api-docs
            - id: leave-service-docs
              uri: lb://leave-service
              predicates:
                - Path=/v3/api-docs/leave-service
              filters:
                - RewritePath=/v3/api-docs/leave-service, /v3/api-docs
            - id: companyinfo-service-docs
              uri: lb://companyinfo-service
              predicates:
                - Path=/v3/api-docs/companyinfo-service
              filters:
                - RewritePath=/v3/api-docs/companyinfo-service, /v3/api-docs
            - id: communication-service-docs
              uri: lb://communication-service
              predicates:
                - Path=/v3/api-docs/communication-service
              filters:
                - RewritePath=/v3/api-docs/communication-service, /v3/api-docs
            - id: attachment-service-docs
              uri: lb://attachment-service
              predicates:
                - Path=/v3/api-docs/attachment-service
              filters:
                - RewritePath=/v3/api-docs/attachment-service, /v3/api-docs

          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/api/**]':
                allowedOrigins:
                  - "http://localhost:3000"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true
              '[/v3/**]':
                allowedOrigins:
                  - "http://localhost:3000"
                allowedMethods:
                  - GET
                  - POST
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
